version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of the project
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_dev
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre

volumes:
  postgres_data: