# Generated by Django 4.0.6 on 2022-07-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_price', models.FloatField()),
            ],
            options={
                'db_table': 'alert',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_category', models.CharField(choices=[('unknown', 'unknown'), ('appliance', 'appliance'), ('clothing', 'clothing')], default='unknown', max_length=100)),
                ('article_type', models.CharField(choices=[('unknown', 'unknown'), ('smartphone', 'smartphone'), ('laptop', 'laptop'), ('speaker', 'speaker'), ('headphone', 'headphone')], default='unknown', max_length=100)),
                ('article_brand', models.CharField(choices=[('unknown', 'unknown'), ('apple', 'apple'), ('samsung', 'samsung'), ('xiaomi', 'xiaomi'), ('sony', 'sony'), ('oppo', 'oppo'), ('lg', 'lg'), ('panasonic', 'panasonic'), ('benq', 'benq'), ('whirlpool', 'whirlpool'), ('bose', 'bose'), ('jbl', 'jbl'), ('lenovo', 'lenovo'), ('acer', 'acer'), ('hp', 'hp'), ('dell', 'dell'), ('go_pro', 'go_pro'), ('microsoft', 'microsoft'), ('HUAWEI', 'HUAWEI'), ('motorola', 'motorola'), ('honor', 'honor'), ('realme', 'realme')], default='unknown', max_length=100)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField()),
                ('price', models.FloatField()),
                ('shipping_price', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article2Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            options={
                'db_table': 'article_2_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('company_type', models.CharField(choices=[('unknown', 'unknown'), ('Technology', 'Technology')], default='unknown', max_length=100)),
                ('note', models.TextField()),
                ('icon_url', models.URLField()),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
            ],
            options={
                'db_table': 'favourite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(blank=True, default='', max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person2Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favourite', models.ForeignKey(db_column='favourite_id', on_delete=django.db.models.deletion.CASCADE, to='core.favourite')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'person_2_favourite',
                'managed': True,
                'unique_together': {('person', 'favourite')},
            },
        ),
        migrations.CreateModel(
            name='Person2Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(db_column='alert_id', on_delete=django.db.models.deletion.CASCADE, to='core.alert')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'person_2_alert',
                'managed': True,
                'unique_together': {('person', 'alert')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='alerts',
            field=models.ManyToManyField(blank=True, through='core.Person2Alert', to='core.alert'),
        ),
        migrations.AddField(
            model_name='person',
            name='favourites',
            field=models.ManyToManyField(blank=True, through='core.Person2Favourite', to='core.favourite'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('articles', models.ManyToManyField(blank=True, through='core.Article2Image', to='core.article')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_prices', to='core.article')),
            ],
            options={
                'db_table': 'historical_price',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='favourite',
            name='persons',
            field=models.ManyToManyField(blank=True, through='core.Person2Favourite', to='core.person'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=1024)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.article')),
            ],
            options={
                'db_table': 'description',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='article2image',
            name='image',
            field=models.ForeignKey(db_column='image_id', on_delete=django.db.models.deletion.CASCADE, to='core.image'),
        ),
        migrations.AddField(
            model_name='article',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.company'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, through='core.Article2Image', to='core.image'),
        ),
        migrations.AddField(
            model_name='alert',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article'),
        ),
        migrations.AddField(
            model_name='alert',
            name='persons',
            field=models.ManyToManyField(blank=True, through='core.Person2Alert', to='core.person'),
        ),
        migrations.AlterUniqueTogether(
            name='article2image',
            unique_together={('article', 'image')},
        ),
    ]
